[package]
name = "binder-host-browser"
version.workspace = true
edition.workspace = true

[dependencies]
binder-rpc = { path = "../binder-rpc" }

serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait = "0.1"
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true